version: "3.8"

services:
  ncc-1701:
    container_name: cockpit_ncc-1701
    image: roalcantara/cockpit:ncc-1701
    labels:
      description: "An opiopnated Dev Environment based on Alpine linux."
      org.opencontainers.image.source: https://github.com/roalcantara/cockpit
    env_file: .env
    build:
      context: .
      target: ncc-1701
      # variables to be used on the image
      args:
        # the user's username
        USERNAME: ${USERNAME:-dev}
        # the user's group
        GROUPNAME: ${GROUPNAME:-wheel}
        # the timezone
        TZ: ${TZ:-America/Sao_Paulo}
        # whether to enable BuildKit - https://docs.docker.com/build/buildkit
        DOCKER_BUILDKIT: ${DOCKER_BUILDKIT:-1}
        # turn on the inline layer caching - https://docs.docker.com/build/buildkit
        BUILDKIT_INLINE_CACHE: ${BUILDKIT_INLINE_CACHE:-1}
        # the human-readable name in the "author" field (who originally wrote the patch).
        GIT_AUTHOR_NAME: ${GIT_AUTHOR_NAME:-Rogério R. Alcântara}
        # the email for the "author" field.
        GIT_AUTHOR_EMAIL: ${GIT_AUTHOR_EMAIL:-rogerio.alcantara@gmail.com}
        # the human name for the "committer" field (who committed the code on behalf of the original author).
        GIT_COMMITTER_NAME: ${GIT_COMMITTER_NAME:-roalcantara}
        # the email address for the "committer" field.
        GIT_COMMITTER_EMAIL: ${GIT_COMMITTER_EMAIL:-rogerio.alcantara@gmail.com}
    # configures service containers to run with an allocated stdin (docker run -i)
    stdin_open: true
    # configure service container to run with a TTY (docker run -t)
    tty: true
