name: Deployment

on:
  release:
    types:
      - published
  workflow_dispatch:

env:
  CI: true
  FORCE_COLOR: true
  DOCKER_BUILDKIT: 1
  BUILDKIT_INLINE_CACHE: 1

defaults:
  run:
    shell: bash

jobs:
  docker:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://hub.docker.com/repository/docker/${{ github.repository }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2.2.1
      - uses: docker/metadata-action@v4.1.1
        id: meta
        with:
          images: ${{ github.repository }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flavor: latest=true
          tags: type=semver,pattern={{version}}
      - uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2.2.1
    - uses: docker/metadata-action@v4.1.1
      id: meta
      with:
        images: ghcr.io/${{ github.repository }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flavor: latest=true
        tags: type=semver,pattern={{version}}
    - uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v3.2.0
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
