name: Release

on:
  push:
    branches:
      - main

env:
  CI: true
  FORCE_COLOR: true
  SEMANTIC_VERSION: 19

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]') && !contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: crazy-max/ghaction-import-gpg@v5.2.0
        id: gpg
        with:
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_push_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          fingerprint: ${{ secrets.GPG_FINGERPRINT }}
          git_committer_name: ${{ secrets.GPG_COMMITTER_NAME }}
          git_committer_email: ${{ secrets.GPG_COMMITTER_EMAIL }}
      - if: success()
        shell: bash
        run: |
          echo ${{ steps.gpg.outputs.fingerprint }}
          echo ${{ steps.gpg.outputs.keyid }}
          echo ${{ steps.gpg.outputs.name }}
          echo ${{ steps.gpg.outputs.email }}
      - uses: dkhunt27/semantic-release-action@v3.2.0-beta1
        if: success()
        id: semantic
        with:
          semantic_version: ${{ inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: steps.semantic.outputs.new_release_published == 'true'
        shell: bash
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}
